### UserAPI

###  API030 로그인
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "userId" : "master",
  "password" : "1234"
}

###  API006 팀원이 아닌 사용자 조회
GET http://localhost:8080/api/users/exclusion/team/10
Content-Type: application/json


